services:

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    image: umesh85m/healthcare-frontend:latest
    container_name: healthcare-frontend
    ports:
      - "80:80"
    restart: always
    depends_on:
      - backend
      - database

  backend:
    image: nginx:alpine
    container_name: healthcare-backend
    restart: always

  database:
    image: mysql:8.4
    container_name: healthcare-database
    restart: always
    environment:
      MYSQL_DATABASE: healthcare_db
      MYSQL_USER: healthcare_user
      MYSQL_PASSWORD: Healthcare@123
      MYSQL_ROOT_PASSWORD: HealthcareRoot@123
    volumes:
      - healthcare_db_data:/var/lib/mysql
    restart: always

volumes:
  healthcare_db_data:
